IF DB_ID(N'TailorERP') IS NULL
BEGIN
    CREATE DATABASE TailorERP;
END;
GO

ALTER DATABASE TailorERP SET READ_COMMITTED_SNAPSHOT ON WITH ROLLBACK IMMEDIATE;
GO

USE TailorERP;
GO

IF SCHEMA_ID(N'sec') IS NULL
    EXEC(N'CREATE SCHEMA sec AUTHORIZATION dbo;');
GO
